<div class="main">
<h1>Мои контакты</h1>
<p></p>

<div class="text-center"><img src="/img/conact1.jpg" alt="Мои контакты" class="img"></div>


<dl class="dl-horizontal">
  <dt>Я в ВК</dt>
  <dd><a href="https://vk.com/denisr74"  target="_blank" rel="noopener noreferrer">Знакомиться - Жми сюда!</a></dd>
</dl>

<h3>Мои хобби</h3>
<dl class="dl-horizontal">
  <dt>Путешествия и природа</dt>
  <dd><a href="https://vk.com/den_ural_tour" target="_blank" rel="noopener noreferrer">Туры по Уралу | Отдохни и вдохновись природой!</a></dd>
  <dt>Музыка</dt>
  <dd><a href="https://vk.com/4d_creativeassociation" target="_blank" rel="noopener noreferrer">Творческое объединение 4D - повод для настроения</a></dd>
</dl>

</div>